//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Currency2StringConverter.ConverterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConverterServiceReference.IConverterService")]
    public interface IConverterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/TestConnetion", ReplyAction="http://tempuri.org/IConverterService/TestConnetionResponse")]
        string TestConnetion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/TestConnetion", ReplyAction="http://tempuri.org/IConverterService/TestConnetionResponse")]
        System.Threading.Tasks.Task<string> TestConnetionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/ConvertString", ReplyAction="http://tempuri.org/IConverterService/ConvertStringResponse")]
        string ConvertString(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/ConvertString", ReplyAction="http://tempuri.org/IConverterService/ConvertStringResponse")]
        System.Threading.Tasks.Task<string> ConvertStringAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConverterServiceChannel : Currency2StringConverter.ConverterServiceReference.IConverterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConverterServiceClient : System.ServiceModel.ClientBase<Currency2StringConverter.ConverterServiceReference.IConverterService>, Currency2StringConverter.ConverterServiceReference.IConverterService {
        
        public ConverterServiceClient() {
        }
        
        public ConverterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConverterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestConnetion() {
            return base.Channel.TestConnetion();
        }
        
        public System.Threading.Tasks.Task<string> TestConnetionAsync() {
            return base.Channel.TestConnetionAsync();
        }
        
        public string ConvertString(string value) {
            return base.Channel.ConvertString(value);
        }
        
        public System.Threading.Tasks.Task<string> ConvertStringAsync(string value) {
            return base.Channel.ConvertStringAsync(value);
        }
    }
}
